wllvm: Fix undefined reference to level4_kernel_pgt
The original code was programmed so that optimizations
would detect the constant bool from check_la57_support()
and optimize it away together with the basic block that
contains the reference to the symbol.